return {
  pde = {
    ai = true,
    angular = false,
    cpp = false,
    csharp = false,
    docker = true,
    elixir = true,
    flutter = true,
    go = true,
    html = true,
    java = false,
    json = true,
    julia = false,
    jupyter = true,
    kotlin = false,
    lua = true,
    python = true,
    r = false,
    react = true,
    ruby = true,
    rust = true,
    scala = true,
    solidity = true,
    svelte = true,
    tailwind = true,
    terraform = false,
    typescript = true,
    vuejs = true,
  },
}
